FROM python:3.8-slim

COPY requirements-dagster.txt

RUN pip install --no-cache-dir -r requirements-dagster.txt

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml $DAGSTER_HOME

COPY workspace.yaml.ecs $DAGSTER_HOME/workspace.yaml

WORKDIR $DAGSTER_HOME
